### ISSUE TITLE
Disable the option to toggle itemframes visibility

### ISSUE THREAD

**Issue by ItzRobin** [Wolfieheart/ArmorStandEditor#104]
### Is your feature request related to a problem?

I want to prevent the fact that my players can change a regular item frame in a invisible itemframe

### Describe the solution you'd like.

I would prefer a permission of a simple setting in the config

### Describe alternatives you've considered.

I have found a fork but I think this variant is more stable so I hope there can be a solution for this

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by ItzRobin** [comment]
Update! This problem has been fixed by generating a new and clean config!

**Comment by Wolfieheart** [comment]
Haha no worries - Glad the clean config fixed it ;)
