### ISSUE TITLE
Naming and adding a description to the subject of the rack editor

### ISSUE THREAD

**Issue by xOpasik** [Wolfieheart/ArmorStandEditor#118]
### Is your feature request related to a problem?

To enable the crafting of this item

### Describe the solution you'd like.

I would like to ask you to add the possibility:

- Item naming for editing stands
- Adding a description
- Adding any enchant

### Describe alternatives you've considered.

-

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Wolfieheart** [comment]
- Item naming for editing stands
Can you please further clarify as to what you mean by this as Naming ArmorStands is already apart of the Base Pack

- Adding a description
Can you clarify this?

- Adding any enchant
This might be tricking and something that I am not comfortable adding at this moment

**Comment by xOpasik** [comment]
This is what I wrote about with you over a month ago

**Comment by xOpasik** [comment]
![image](https://user-images.githubusercontent.com/105610066/189634674-64d2ad0d-f38a-4e4b-ab0f-6db9763df3e4.png)

Ability to name and add an item description in config

**Comment by Wolfieheart** [comment]
Ah yeah. Forgive me as with not having worked and being human and not
remembering the outcome of certain decisions, i misremembered.

I think i wrote a hint for this somewhere. I will have a look and check it
out soon.

**Comment by xOpasik** [comment]
Oh, sorry that I dare to write and remind you.

**Comment by xOpasik** [comment]
After a month, I remind you, because I'm just waiting to be able to introduce this player editor.

Have I written to you day by day about it? A month without asking, reminders, is a long period

**Comment by Wolfieheart** [comment]
I understand. I am sorry for putting it off for so long but other priorities at the moment. I will try to have a  look into this today :)

**Comment by Wolfieheart** [comment]
Checking already in to stuff I need to do: 

Item Descriptions as you call it are already available through the Lore feature that this plugin has available. Thats per research on the SpigotMC Forums

The Item Name I will look into adding now :)

**Comment by Wolfieheart** [comment]
#122 wil llcose this and will require some testing from my side but I can not test it right now as I am at work and have worked on this over lunch :) 

If you want to attempt to test this yourself, then please do so by downloading https://cdn.discordapp.com/attachments/942106460207337563/1018849097656057856/armorstandeditor-1.19.2-37.3.jar

And setting the 2 Variables Regarding requireToolName and the toolName itself and renaming your tool in an Anvil or giving yourself a tool with that name.

**Comment by xOpasik** [comment]
![image](https://user-images.githubusercontent.com/105610066/189683999-2d55e0fa-951e-4da6-b35b-270c395e856e.png)

So it is supposed to work on the principle, you add a description in the item and after that it is "searched"?

Can you make any name you want?

**Comment by Wolfieheart** [comment]
Exactly. It looks for the item that is currently being held that had that
name and that description

**Comment by xOpasik** [comment]
In fact, great if a hex gradient was implemented sometime

**Comment by xOpasik** [comment]
![image](https://user-images.githubusercontent.com/105610066/189687740-d9825c8c-37a1-40e2-b81e-5c603f3b404c.png)

**Comment by Wolfieheart** [comment]
I've had this suggestion before.

At the moment I don't think it would be possible to do hex without a major
overhaul of things.

It's on my backlog to do at some point but isn't high priority:)

**Comment by xOpasik** [comment]
requireToolLore: true
toolLore: '&7testowy'

And what to do when I want to make 1-2 lines of description?

**Comment by xOpasik** [comment]
Out of curiosity, did you remove the server discord or, under the influence of emotions, did you ban me?

**Comment by Wolfieheart** [comment]
This i am not sure of as I haven't fully tested this myself. And I removed
the server as it wasn't active anymore.

**Comment by Wolfieheart** [comment]
This has now been tested and will be closed when #122 is merged in :) Expect it to be available in a few hours

**Comment by xOpasik** [comment]
In fact, yes, fact, I also tested myself and it worked, but I did not write forgive

**Comment by Wolfieheart** [comment]
No worries, thank you for testing and again I apologise for the long delay with waiting to get this done. :) It shouldnt happen in the future and I have begun work to finalise 1.19.2-38 :)
