### ISSUE TITLE
[Bug]: Error Enabling ArmorStandEditor v1.19.2-37.2 on paper 1.90

### ISSUE THREAD

**Issue by FatherWh0** [Wolfieheart/ArmorStandEditor#123]
### Expected behavior

Enabled successfully.

### Observed/Actual behavior

Begins to load then errors.

### Steps/models to reproduce

attempt to load ArmorStandEditor v1.19.2-37.2.

### Plugin list

EssentialsX, shopkeepers, worldedit, worldguard, viaversion.

### Plugin Version

ArmorStandEditor v1.19.2-37.2

### Server Version

Paper-66 mc1.19

**Comment by FatherWh0** [comment]
https://pastebin.com/U7rPkZ6T

**Comment by Wolfieheart** [comment]
Will check on this now. Thanks for reporting.

**Comment by Wolfieheart** [comment]
Unable to reproduce with Paper 144 and its strange that this only coming now as nothing has changed there since 1.19-35

**Comment by Wolfieheart** [comment]
Also unable to reproduce with Paper66 1.19 :(

**Comment by FatherWh0** [comment]
I can continue to run armorstandeditor-1.18.2-34.2 until something changes. Thx for your help.
