### ISSUE TITLE
[Bug]: Using griefprevention, they are able to steal items from claims that don't have permission 

### ISSUE THREAD

**Issue by thiagogebrimm** [Wolfieheart/ArmorStandEditor#145]
### Expected behavior

without permission in the claim was not to be able to edit armor  stand

### Observed/Actual behavior

even without having /trust in a claim they can get things from the armor stand

### Steps/models to reproduce

use the editor on a claim you don't have permission

### Plugin list

AdvancedEnchantments, AngelChest, ArmorStandEditor, BanFromClaim, ChestSort, Chunky, CoreProtect, Essentials, EssentialsSpawn, FastAsyncWorldEdit, GP-Revo-Addons, GriefPrevention, HolographicDisplays, Insights, Legendchat, LuckPerms, mcMMO, PlaceholderAPI, ProtocolLib, QuickShop, RealEstate, RevoAllAchievements, RevoBlockPhantom, RevoBookFix, RevoClaimExpiration, RevoDiscordAnnounce, RevoEssentialsUtils, RevoLeaderTag, RevoLiga, RevoLogger, RevoLuz, RevoMapCopyright, RevoNightPvP, RevoPlayerWorldCounter, RevoProfile, RevoRewards, RevoVoidVersiom, SimpleClans, SimplePets, SkinsRestorer, SODiscordSync, SODuels, SOEconomy, TAB, Vault, WorldGuard

### Plugin Version

1.19.2-38

### Server Version

1.19.2
Purpur

**Comment by Wolfieheart** [comment]
And you are sure that the grank that is taking the items does not have the permission: asedit.ignoreProtection.griefPrevention or any of the asedit.ignoreProtection permissions?

and was this happening in prior versions or only just in 1.19.2-38?

**Comment by thiagogebrimm** [comment]
Yes

I don't know for sure, the bug was discovered this week

**Comment by Wolfieheart** [comment]
Can you also check with 1.19.3-36 and see if it's also the case there?

**Comment by thiagogebrimm** [comment]
in the 1.19.3-36 works correctly

**Comment by thiagogebrimm** [comment]
It looks like the plugin is loading before griefprevention, when reloading using plugman it works correctly

**Comment by Wolfieheart** [comment]
Huh that is interesting. Will have to check that out - Part of the investigations tonight ;)

**Comment by Wolfieheart** [comment]
Interesting this cause when testing on 1.19.3-DEV, it does not appear to be an issue 
![image](https://user-images.githubusercontent.com/18635695/206917480-cd5c9df9-4573-4297-b0f9-5bb092f86d83.png)
