### ISSUE TITLE
[Bug]: Russian Translation not being recognised in the Plugin Files

### ISSUE THREAD

**Issue by SlavaKiller2020** [Wolfieheart/ArmorStandEditor#159]
### Expected behavior

I wanted to make a translation for the plugin into my own language.

### Observed/Actual behavior

The plugin does not see the translation file

### Steps/models to reproduce

I created a copy of the English translation file and translated it, renamed it and put the name in config.yml

### Plugin list

CoreProtect
Dynmap
EssentialsX
EssentialsXChat
FancyBags
HeadDataBase
LuckPerms
MultiMOTD
SimpleSit
SkipNight
TAB
Vault
WorldEdit
WorldsColor

### Plugin Version

1.19.2-38

### Server Version

1.16.5 spigot

### Other

I added an archive because uml file cannot be added
[lang file.zip](https://github.com/Wolfieheart/ArmorStandEditor/files/10045421/lang.file.zip)

Sorry for the mistakes, I don't know English well

**Comment by Wolfieheart** [comment]
Sorry for the delay on this! Github has not been giving me notifications. Will Investigate tonight!

**Comment by Wolfieheart** [comment]
Definately interesting.... Might be that the Language File isnt being registered when loading. Investigation Initial Complete... Hopefully gonna fix it with the 1.19.3 Update

**Comment by Wolfieheart** [comment]
Also appears that the file has some errors, as when testing with: https://github.com/Wolfieheart/ArmorStandEditor/blob/master/src/main/resources/lang/ru_RU.yml

The issue does not appear. However the origin of the bug is that the Config isnt added. Therefore fixed with 1.19.3-39
