### ISSUE TITLE
BentoBox support

### ISSUE THREAD

**Issue by VozikCZE** [Wolfieheart/ArmorStandEditor#182]
### Is your feature request related to a problem?

Players can edit armorstands on all islands

### Describe the solution you'd like.

Implement protection from BentoBox plugin 

### Describe alternatives you've considered.

-

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

Bentobox: https://github.com/BentoBoxWorld/BentoBox

**Comment by Wolfieheart** [comment]
Testing of this currently underway. Will be fixed in the next update hopefully :D
