### ISSUE TITLE
[Bug]: Rightclicking an armorstand in a Lands claim drops an error in Console

### ISSUE THREAD

**Issue by Omarlatif** [Wolfieheart/ArmorStandEditor#203]
### Expected behavior

We expect there not to be an error

### Observed/Actual behavior

https://pastebin.com/4riXpzd5

### Steps/models to reproduce

Install Lands
Install ASE
Place an armorstand
Right click armorstand

### Plugin list

Not required

### Plugin Version

1.19.4-40

### Server Version

Current: git-Purpur-1912 (MC: 1.19.3)*

**Comment by Wolfieheart** [comment]
Can you  give this a try for me and let me know if it stops the console spamming: https://cdn.discordapp.com/attachments/1088160909597360228/1088161073414287380/armorstandeditor-1.19.4-40.1.jar

That on my end should work, but I want to double check that this fixes your issue :)
