### ISSUE TITLE
[Bug]: toolLore not working 

### ISSUE THREAD

**Issue by DreiFxn** [Wolfieheart/ArmorStandEditor#210]
### Expected behavior

The item lore and the "ToolLore" set in the config match and the edit screen opens.

### Observed/Actual behavior

The Hud does not open

### Steps/models to reproduce

1. Set requireToolLore to "true" & set toolLore: Test
2. Upload config and restart server
3. Join server and create item [set in config] with lore: Test
4. Try to open editing HUD
5. Nothing should happen

### Plugin list

Plugins (30): ArmorStandEditor, Bank, ChestShop, ChestShop-towny, Chunkmaster, Core, CustomCrafting, DecentHolograms, DeluxeMenus, dynmap, Dynmap-Towny, Essentials, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), Graves, LuckPerms, Maintenance, mcMMO, MobsToEggs, PlaceholderAPI, PlayerStats, ProtocolLib, RealScoreboard, TAB, Towny, Vault, VentureChat, WolfyUtilities, WorldBorder, WorldGuard

### Plugin Version

1.19.4-40.1

### Server Version

git-Paper-307 (MC: 1.19.2)

**Comment by Wolfieheart** [comment]
10/10 Catch - Successful Reproduction :)
