### ISSUE TITLE
Folia support.

### ISSUE THREAD

**Issue by kugge** [Wolfieheart/ArmorStandEditor#216]
Hello !  😄 
I added Folia support with reflection.
Should I PR thoses changes ? If yes, to dev/119403 or master ?
I didn't know where to contact you, since your discord DMs are closed and there's no discord support (i think)

**Comment by Wolfieheart** [comment]
Oh Hi there,

Yeah sorry my DMs are closed on Discord as I got hacked last year, got my account back and have my security up since. Go ahead and create a PR from Master and bump the version to 1.19.4-41 :)
