### ISSUE TITLE
[Bug]: option requireToolLore is ignored

### ISSUE THREAD

**Issue by DexterSK** [Wolfieheart/ArmorStandEditor#264]
### Expected behavior

Right click with defined **tool** and **toolLore** will open ASE menu

`
#Name of the edit tool's item Material.
tool: FEATHER
#(Optional) The first "Lore" entry that the plugin looks for to identify the edit tool.
requireToolLore: true
toolLore: "#"
`

### Observed/Actual behavior

Right click with defined tool without specified lore won't open ASE menu

### Steps/models to reproduce

Right click with vanilla feather without any lore

### Plugin list

doesn't matter

### Plugin Version

armorstandeditor-1.19.4-42.1

### Server Version

git-Purpur-1968 (MC: 1.19.4)

### Other

Sorry for bad english :D

**Comment by Wolfieheart** [comment]
Nicely found - Was pretty sure I covered this in testing but Nicely found never the less, Will check it with ASE 1.20.0-43 DEV and see what comes ;)

**Comment by Wolfieheart** [comment]
Hrmmm this is happening mostly because it is expecting the ToolLore to be in the format specified in the config file, as part of the implementation for MultiLine ToolLore which means, it is always going to expect a list to be present.

``` #(Optional) The first "Lore" entry that the plugin looks for to identify the edit tool. - Now has MultiLine Support
requireToolLore: false
toolLore:
  - "TIME TO GET REALLY"
  - "REALLY DANGEROUS!"
```

While this is not a bug, HOWEVER, I am going to add the remark in the Config.yml to keep it in a list in order for ToolLore to work :)

**Comment by DexterSK** [comment]
oh thanks 

> 

Hello, i changed it to list but now it just won't work. Do i need to specify colors or?
![world_selection](https://github.com/Wolfieheart/ArmorStandEditor/assets/4334671/e4c39b7c-cf1b-4460-8f3d-f97e5c78f0a6)

**Comment by DexterSK** [comment]
yup its working now, thanks!
