### ISSUE TITLE
Hologram NameTag Support Feature (Hologram over the ArmorStand) 

### ISSUE THREAD

**Issue by Fynn9518** [Wolfieheart/ArmorStandEditor#265]
### Is your feature request related to a problem?

I think it would be good if you could create holograms directly via commands or the menu, because then the holograms are always in the right position. When I create them with an external hologram plugin, it's difficult to find the perfect position.

![Screenshot_1](https://github.com/Wolfieheart/ArmorStandEditor/assets/132841252/eed646e5-e0b4-4061-a3b1-dcddfd161b15)

Don't wonder. The Text in the screenshot is German.

### Describe the solution you'd like.

Maybe you can install a button in the ASE menu that prompts you to send the text with hex codes or the normal color codes to the chat and this is then displayed as a hologram from a fixed point

### Describe alternatives you've considered.

It is possible to display these holograms via other hologram plugins, but I would like it if this were possible directly via ASE. Then you could also release the users.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

adding the following permissions nodes:

asedit.nametag
asedit.nametag.color (1,2,3,4,5,6,7,8,9,0,a,b,c,d,e,f)
asedit.nametag.styling (n,m,l,o)

**Comment by Wolfieheart** [comment]
Updating the title to be more clear of what this asking :) - Will do an initial Investigation some time after the 1.20 Public Release.
