### ISSUE TITLE
[Bug]: Console can't run reload command

### ISSUE THREAD

**Issue by qbasty** [Wolfieheart/ArmorStandEditor#267]
### Expected behavior

Console can't run "armorstandeditor reload".

### Observed/Actual behavior

armorstandeditor reload
[12:29:44 INFO]: You don't have permission to use this!

### Steps/models to reproduce

Run the command:
/lp group default permission set asedit.* false

Then try in console to run any asedit command, OPs can't run anything as well.

### Plugin list

LuckPerms is needed for this.

### Plugin Version

armorstandeditor-1.19.4-42.1.jar

### Server Version

This server is running Kaiiju version git-Kaiiju-"d9ad730" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: d9ad730 on HEAD)
You are 5 version(s) behind
Download the new version at: https://github.com/KaiijuMC/Kaiiju/releases

**Comment by Wolfieheart** [comment]
Console was never able to run any of the ArmorStandEditor commands. I would need to work out how we can make that command be able to be ran from Console.

**Comment by Wolfieheart** [comment]
Is in part linked to the issue that CommandSender in CommandEx is cast to a player ... Might require either a console ONLY Version or CommandEx might be due a refactor....

**Comment by Wolfieheart** [comment]
Alrighty Fix Incoming for this :D  - I got motivation to fix this now - HOWEVER this will only work for `Update, Reload. Help/? and Version`

All other commands attempted to be ran from console will FAIL outright!

**Comment by Wolfieheart** [comment]
Also going to backtrack on Update as it prints to console every 24 hours if OPs dont get notifications
