### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Nachos404** [Wolfieheart/ArmorStandEditor#287]
### Expected behavior

able to download on spigot

### Observed/Actual behavior

Cant download plugin on spigot says no permission

### Steps/models to reproduce

try to download plugin

### Plugin list

a

### Plugin Version

1.20

### Server Version

1.20

**Comment by Wolfieheart** [comment]
I am currently banned on Spigot for the ArmorStandEditor Resource - The only current ways to download the Plugin can be found in the Readme File.
