### ISSUE TITLE
Add support for Grieveprevention to fix a bug

### ISSUE THREAD

**Issue by Jeroen123TC** [Wolfieheart/ArmorStandEditor#306]
### Is your feature request related to a problem?

Heyy man! Great plugin, i only missing somethin in it. 
On my survival server we use the plugin Grieveprevention to manage the claims. But players can made itemframes invisible on other players there claims.

### Describe the solution you'd like.

Is it possible that you add support for grieveprevention so players can only edit itemframs if they have trust on the claim or are claimowners?

### Describe alternatives you've considered.

there is no other solution to fix my problem D:

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Wolfieheart** [comment]
Do you mean GriefPrevention?

If you do then the protection should already be there...

**Comment by Jeroen123TC** [comment]
> Do you mean GriefPrevention?
> 
> If you do then the protection should already be there...

Ohh excuse me xD, yes Griefprevention, i have now the problem that players can makd eachothers itemframes invisible.

**Comment by Wolfieheart** [comment]
Nromally that should fall into the GriefPreventionProtection class.

Do you have `asedit.ignoreProtection.griefPrevention` set true for anyone below a rank like Admin/Developer/Mod/Owner?

**Comment by Jeroen123TC** [comment]
> Nromally that should fall into the GriefPreventionProtection class.
> 
> Do you have `asedit.ignoreProtection.griefPrevention` set true for anyone below a rank like Admin/Developer/Mod/Owner?

In the griefprevention plugin?

**Comment by Wolfieheart** [comment]
No in your permission manager for any rank.

**Comment by Jeroen123TC** [comment]
> No in your permission manager for any rank.
> […](#)

alright, i will check the permission for it.
