### ISSUE TITLE
Toggle destroying armor stands

### ISSUE THREAD

**Issue by Folas1337** [Wolfieheart/ArmorStandEditor#309]
### Is your feature request related to a problem?

I have a few heavy users for ASE on my creative server and they work a lot with armor stands in quite small spaces which sometimes leads to them breaking armor stands when they didn't intend to do so and some frustration from this problem.

### Describe the solution you'd like.

The solution I am envisioning is a toggle in the ASE menu where you can disable breaking armor stands. That way you could still break them in creative if you wanted to but you wouldn't do so if you had it toggled off.
Only issue I can see with this is that people could be confused if they rejoin and still have it on and then wonder why they can't break armor stands but for me that would be a sacrifice I'm willing to make.

I would however make it toggleable in the config and have it off by default.

### Describe alternatives you've considered.

I have tried making the armor stand invulnerable but that's ignored if you're in creative mode, I have also searched for plugins that already do this but came up empty handed :(

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Wolfieheart** [comment]
This is an interesting one, cause I do wonder if we could map it to just be behind a permission.

An idea of what this could look like is:

```java
   
    @EventHandler(priority = EventPriority.LOWEST)
    void onArmorStandBreak (BlockBreakEvent event){
        //Disables breaking an ArmorStand in Creative Mode ?
        if (ignoreNextInteract) return;
        if (event.getBlock().getType() != Material.ARMOR_STAND) return;
        Player player = event.getPlayer();

        if(player.hasPermission("asedit.disableCreativeBreak")){
            Block block = event.getBlock();
            if(block.getType() == Material.ARMOR_STAND && player.getGameMode() == GameMode.CREATIVE){
                event.setCancelled(true);
            }
        }
    }
```

But im now trying to work out how to map this to the toggles like we have for Disable Slots

**Comment by Folas1337** [comment]
I can probably make a permission work as well but I would certainly like to see it implemented into the menu of the plugin.

I hope it's going to work out and I'll just patiently wait (unless you need anything else from me?)

**Comment by Wolfieheart** [comment]
ACTUALLY I just throught of a much simpler solution that we can fix already - Lemme write it up and ask if thats OK with you

**Comment by Wolfieheart** [comment]
I consider this more a bug with Invulnerability Toggle. Technically what I would have expected it to do is what this exactly wants to solve with an extra option.

We just need to add an event to listen on the ArmorStand attempting to be damaged:

```java
    @EventHandler(priority = EventPriority.LOW, ignoreCancelled = true)
    void onArmorStandBreak (EntityDamageByEntityEvent event) {
        //Disables breaking an ArmorStand in Creative Mode
        if (!(event.getDamager() instanceof Player)) return;   // If we arent a player -- Ignore
        if (!(event.getEntity() instanceof ArmorStand)) return; // If we arent an ArmorStand -- ignore

        //Get the Player doing Damage
        Player player = (Player) event.getDamager();

        //Get the ArmorSTand
        if (event.getEntity() instanceof ArmorStand entityAS){
            if (entityAS.isInvulnerable() && player.getGameMode() == GameMode.CREATIVE) {
                //If the player is in Creative - Cancel the Event
                event.setCancelled(true);
            }
        }
    }
```

Therefore we dont need an extra menu toggle, in this case, we just check if the Player is in Creative and if the ArmorStand is invulnerable, if this is the case, it shouldnt ever break/

**Comment by Wolfieheart** [comment]
Ok I have a solution.

Long STory Short: Its an Invulnerability Bug.

The Code behind it now:
```java
    @EventHandler(priority = EventPriority.LOW, ignoreCancelled = true)
    void onArmorStandBreak (EntityDamageByEntityEvent event) {
        //Disables breaking an ArmorStand in Creative Mode
        if (!(event.getDamager() instanceof Player)) return;   // If we arent a player -- Ignore
        if (!(event.getEntity() instanceof ArmorStand)) return; // If we arent an ArmorStand -- ignore

        //Get the ArmorStand
        if (event.getEntity() instanceof ArmorStand entityAS){
            //CHECK: Vulnerability State and GameMode State
            if (entityAS.isInvulnerable() && event.getDamager() instanceof Player p) {
                if(p.getGameMode() == GameMode.CREATIVE) {
                    //If the player is in Creative and the ArmorStand is Invulnerabile - Cancel the Event
                    event.setCancelled(true);
                }
            }
        }
    }
    ```

**Comment by Wolfieheart** [comment]
Showing the Fix in Action: 

https://github.com/Wolfieheart/ArmorStandEditor/assets/18635695/d25f8e13-8bbc-4bac-8ccb-bba73ddb9887

**Comment by Folas1337** [comment]
Hecc yeah this is great! Looking forward to the release! 👍
