### ISSUE TITLE
Options for setting allowed worlds

### ISSUE THREAD

**Issue by Complex1t** [Wolfieheart/ArmorStandEditor#315]
### Is your feature request related to a problem?

I'd like to keep FLINT as the ASE tool, but I have items that also use FLINT for other interactions in certain worlds. Therefore players can accidentally open the ASE GUI in worlds they shouldn't be able to.

### Describe the solution you'd like.

Something along the lines of:

```
# ASE will only work on worlds listed here
allowed-worlds:
- world_a
- world_b
- world_c
```

With the above configuration, ASE will only work in the worlds listed above. In worlds not listed above, right-clicking flint won't do anything.

### Describe alternatives you've considered.

I've tried using LuckPerms contexts to only give out ASE permissions in certain worlds, but to no avail. I've found that I need to negate the `asedit.*` permission to actually prevent the GUI from opening at all, but with LuckPerms it is not possible to set negated world contexts. I have a dungeon system that creates constantly changing world names, so it is not possible for me to simply set the `asedit.*` permission to false in worlds I don't want ASE activating.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Wolfieheart** [comment]
Hey there, I had a look at this and there will be a build soon available on Development if you wanna try this out

https://github.com/Wolfieheart/ArmorStandEditor/actions/runs/6126405819 - Download the Artifact from there and Unzip the JAR file there within. Please do not use this in production yet, as this is not meant for that.

If you are going to test, please just reply to this with any bugs you find as well as a clear reproduction scenario :)

**Comment by Complex1t** [comment]
Thanks, I tested it and the option seems to be working fine. However, if I try to open the editor in a not allowed world, I get these messages in the chat: https://i.imgur.com/3Nrmyop.png

I regenerated all the plugin's files (including the lang files), and the key for `notincorrectworld` is indeed in en_US.yml, so I think it's a bug.

**Comment by Wolfieheart** [comment]
Ey thanks for that.

I'll have a look further as when testing it locally all was working fine.

**Comment by Wolfieheart** [comment]
Fix should be available on - https://github.com/Wolfieheart/ArmorStandEditor/actions/runs/6136455379

Same as before. Download the Artifact from there and Unzip the JAR file there within.
