### ISSUE TITLE
armorstand

### ISSUE THREAD

**Issue by 4kkkri** [Wolfieheart/ArmorStandEditor#321]
### Expected behavior

invisible armorstand

### Observed/Actual behavior

armorstand don't become invisible

### Steps/models to reproduce

server on purpur

### Plugin list

chunky, spark, skinrestorer, armorstandeditor

### Plugin Version

1.20.1-43.2

### Server Version

1.20.1

**Comment by Wolfieheart** [comment]
1) Do you have asedit.togglearmorstandvisibility and asedit.basic set to true in your Permission Manager?
2) Do you have the config Option to toggle Visibility set to true in your config.ynl?
