### ISSUE TITLE
allowed-worlds should be toggle-able/configurable

### ISSUE THREAD

**Issue by Folas1337** [Wolfieheart/ArmorStandEditor#348]
### Is your feature request related to a problem?

Not necessarily, just a problem for me/my setup.

### Describe the solution you'd like.

I deeply hate the allowed-worlds option as I have a server where people can get personal worlds that all have names with UUIDs in them, so I can't list them all.
Instead give us the option to perhaps use something like "all" as a world name or an asterisk (\*) or make an option to turn it into a whitelist instead.

The current setting is not great in my opinion.

### Describe alternatives you've considered.

I tried using "all" or "*" as a world name but they result in the plugin not loading or not doing what I want it to do.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Wolfieheart** [comment]
I will have a look to see if there is a way to do this easily.

**Comment by Wolfieheart** [comment]
Nah I got a better idea for this one and Im really mad at myself for not doing it this way sooner - Thanks for the report!
