### ISSUE TITLE
Config option: Disable-named-armourstand-option

### ISSUE THREAD

**Issue by agoniaprivat** [Wolfieheart/ArmorStandEditor#501]
### Is your feature request related to a problem?

Would fix a lot of incompabilitys from other plugins using armourstands, which is not based on packets.

### Describe the solution you'd like.

A option in config to disable all editing of all "named armourstands", both visible and invisible named armourstands.

### Describe alternatives you've considered.

Other plugins using packets instead of real entitys. However, most plugins used named armourstand. But since this option is configurable, it allows us to find quick fixes.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other
I need it, specially for this plugin which has armourstandnames on all the armourstands it's using:
https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/
.

**Comment by Wolfieheart** [comment]
API is defined but Plugin is Premium.

API says to Import it directly that way, which I dont feel comfortable doing.

**Comment by Wolfieheart** [comment]
It would be no issue to fix, but there is a small problem.

While the plugin has an API, and its clearly defined how to persue it, I will not be handling this immediately, as the way to fix it would break the Spigot Rules regarding the Distribution of Paid/Premium Plugins.

This has lead to ASE getting banned from Spigot in the past.
