### ISSUE TITLE
1.21 BETA Issue Tracker

### ISSUE THREAD

**Issue by Wolfieheart** [Wolfieheart/ArmorStandEditor#547]
Now that 1.21-47 is in BETA: 

- Beta 1: was removed due to no loading allowed in 1.20. Not Intended. Replaced and fixed in Beta 2.
- Beta 2 Link: https://cdn.discordapp.com/attachments/1136566678713552946/1257645511746519120/armorstandeditor-1.21-47.jar

This will serve as the issue tracker in the event that anything is busted.

**Comment by Wolfieheart** [comment]
**Issues fixed in the meantime after Beta 1/2:**
- #546: Appears I forgot a check when doing the upgrade to move to 1.21 which allows loading with a warning in 1.20 (like with 1.17 - 1.19 previously). Fixed in Beta 2

**Other Open Issues:**
-

**Comment by Boddebon** [comment]
> Now that 1.21-47 is in BETA:
> 
> * Beta 1: was removed due to no loading allowed in 1.20. Not Intended. Replaced and fixed in Beta 2.
> * Beta 2 Link: https://cdn.discordapp.com/attachments/1136566678713552946/1257645511746519120/armorstandeditor-1.21-47.jar
> 
> This will serve as the issue tracker in the event that anything is busted.

Sorry, but the link is no longer available, can you re-upload it?

**Comment by Wolfieheart** [comment]
https://cdn.discordapp.com/attachments/1136566678713552946/1257645511746519120/armorstandeditor-1.21-47.jar?ex=66925827&is=669106a7&hm=a0ebc579bc183deaded04a841d95e1ec3333b51e28ee423ec20952ddbc3ec6ae&

That link should work, as its from the same build in the Discord.
________________________________

**Comment by ChrisPatrol** [comment]
Hey! This beta link once again doesn't work. Would it be possible please to get a new link or be directed in the best place where we should be looking out for beta links?
Thanks!

**Comment by Wolfieheart** [comment]
If you join the discord and check out the #ase-testbuild-feed you can find
it there.

The discord is in the readme file at the start of this repository
