### ISSUE TITLE
Request: Option to disable invis item frames or require a permission.

### ISSUE THREAD

**Issue by BigScary** [Wolfieheart/ArmorStandEditor#560]
### Is your feature request related to a problem?

Invis item frames are a rare item on my server, one of a few used to encourage players to do things like attend scheduled social server events. This latest armor stand editor gives them a way of getting them for free. :)

### Describe the solution you'd like.

Similar to other featurtes, please add an option to disable this, or at least require a permission before a player can use it.

### Describe alternatives you've considered.

I considered downgrading to the older version of the plugin, but it doesn't seem to work on 1.21.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Wolfieheart** [comment]
There should already be a permission to stop the ability to turn ItemFrames invisible, have you tried negating: asedit.toggleitemframevisibility ?

**Comment by MinerFixed** [comment]
@Wolfieheart I can confirm, permission _asedit.toggleitemframevisibility_ doesn't work on 1.21, it's a bug. Could you please fix it.

**Comment by Wolfieheart** [comment]
I just tested this locally, and I can not reproduce it on 1.21-47:


  *
Tested with an account with asedit.*: Works as intended as that perm is intended for OP Users
  *
Tested with an account with  `asedit.permpack.basic ` set  `true ` and  `asedit.toggleitemframevisibility ` set  `false `: Item doesnt appear in the menu and when using `/ase mode ItemFrame ` also does not go through.

Either it is a configuration issue where you have invisibleItemFrames true in your config.yml or your permissions are not being negated properly.
________________________________
