### ISSUE TITLE
[Bug]: When translating configuration lines in the en_US.yml file, the presets stop working

### ISSUE THREAD

**Issue by OperVaite** [Wolfieheart/ArmorStandEditor#571]
### Expected behavior

When translating lines, the functionality must be preserved.

### Observed/Actual behavior

After translating the lines, the presets stopped working. If the translation does not change, i.e. the lines remain in English, the presets work.

### Steps/models to reproduce

https://github.com/user-attachments/assets/dd775e40-1900-4d3a-9d0c-18188358157c

### Plugin list

ArmorStandEditor, Essentinalsx,Chatty

### Plugin Version

ArmorStandEditor-Reborn 1.21-47

### Server Version

Papper 1.21

**Comment by Wolfieheart** [comment]
Discovered the issue, https://github.com/Wolfieheart/ArmorStandEditor/blob/master/src/main/java/io/github/rypofalem/armorstandeditor/menu/PresetArmorPosesMenu.java#L45-L59

Are all hardcoded and dont take the Translated Name. TOp find - Surprised no one noticed it sooner! Fix incoming!

**Comment by Wolfieheart** [comment]
Should be fixed as of [ASE ](https://github.com/Wolfieheart/ArmorStandEditor/pull/586)
