### ISSUE TITLE
[Bug]: ReNameing Doesn't Render

### ISSUE THREAD

**Issue by Ozphilo** [Wolfieheart/ArmorStandEditor#595]
### Expected behavior

After naming a name tag, expectation is to see a name on the armor stand above it with the name and color

### Observed/Actual behavior

Not seeing a name how ever still confirming the name tag was consumed and the name is on the armor stand when in the inventory of the player.

### Steps/models to reproduce

get anvil, name name tag, use color if desired, use on armor stand

### Plugin list

Armor Stand Editor Reborn
Chunky
CoreProtect
Durability Alert
LuckPerms
Maintenance
MobDMZ
Multiverse-Core
Multiverse-Portals

PaperTweaks
PaperTweaks Modules Enabled v
Player Head Drops
More Mob Drops
Silence Mobs
AFK Display
Fast Leaf Decay
Kill Empty Boats
Wandering Trades

SooperDooperScooper
Spark
TabTPS
VoiceChat
WorldEdit

### Plugin Version

1.21-47

### Server Version

Paper version 1.21.1-74

### Other

Have confirmed on other server environments as well using new versions of paper and different plug in configurations, we have about 4 or 5 servers running this plug in. Thanks for all the help :)

**Comment by Wolfieheart** [comment]
Has been reported and should be fixed in 1.21.1-47.1 : I still need to do the release for that, thanks for the reminder :)
