### ISSUE TITLE
Placement tool abuse

### ISSUE THREAD

**Issue by Kyrobi** [Wolfieheart/ArmorStandEditor#80]
### Is your feature request related to a problem?

Limit the palcement feature up to one block maximum (or not out of the block it's placed on.) Right now, players are able to create an armor stand and they use the placement tool to move the armor stand into protected regions. This also goes for players moving the armor stand out of their designated building region.

### Describe the solution you'd like.

Implement a that allows you to specify how much an armor stand can be moved with the placement feature.

### Describe alternatives you've considered.

N/A

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

N/A

**Comment by Wolfieheart** [comment]
I assume this also occurs in 1.19-35 Pre Builds as well, as this sounds like something with WorldGuard and flags. 

Can you confirm and give a list of plugins before I go further :) ?

**Comment by Kyrobi** [comment]
I am using 1.18 at the moment. Here are my plugins
![image](https://user-images.githubusercontent.com/20980266/173311318-37d8219b-e0f8-46a2-baf8-d744f8bb1b93.png)

**Comment by Wolfieheart** [comment]
Ok will Have a further look later this week. Busy with a Windows Reinstall and Upgrading to 1.19. Thanks for the PLugin List :)

**Comment by Wolfieheart** [comment]
Also adding this to #40 for Investigation. It might be only implemented in 1.19-36 as I am working on Finalizing that update. Could also be fixed with WorldGuard, remains to be seen ;)
