### ISSUE TITLE
Option to disable update check entirely.

### ISSUE THREAD

**Issue by mibby** [Wolfieheart/ArmorStandEditor#86]
### Is your feature request related to a problem?

![link](https://i.imgur.com/ZV0lOvR.png)

### Describe the solution you'd like.

Option to disable update check entirely when you know what you are doing and using dev builds.

### Describe alternatives you've considered.

Complaining.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

I'm assuming this config option was removed since it is no longer in the latest config.yml.

```
#Set this to allow your operators to get messages w.r.t Plugin updates
opUpdateNotification: false
```

**Comment by Wolfieheart** [comment]
Surprising that it doesnt look immediately from Spigot instead of checking Github. 

Unless I missed something when doing the change between versions, but accepted as a result.

**Comment by Wolfieheart** [comment]
I assume that happens both on Join and when doing /ase version or /ase update ?

**Comment by mibby** [comment]
Yes, that's correct. I joined as someone who has a ``*`` wildcard permission. Not OP, but essenetially OP with all permission nodes. Also occurs when doing ``/ase version``.

**Comment by Wolfieheart** [comment]
Thean thats part of the API call with people having the ase.update permission.

I might have to make that a permission that is distinctly given and not part of a permission pack. Can you try denying it on a user that is Not OP and seeing if the message appears on join and with /ase version ?

**Comment by Wolfieheart** [comment]
Implementation is the following:

1) Rework of the UpdateChecker part to have a notify that outputs to console and if user is OP they get a notification as well:
`    private void runUpdateChecker() {
        UpdateChecker.init(this, SPIGOT_RESOURCE_ID)
                .setDownloadLink("https://www.spigotmc.org/resources/armorstandeditor-reborn.94503/")
                .setChangelogLink("https://www.spigotmc.org/resources/armorstandeditor-reborn.94503/history")
                .setNotifyOpsOnJoin(true)
                .setNotifyByPermissionOnJoin("asedit.update")
                .setColoredConsoleOutput(true)
                .setUserAgent(new UserAgentBuilder().addPluginNameAndVersion().addServerVersion())
                .checkEveryXHours(72) //Warn people every 72 hours
                .checkNow();
    }`
    
therefore would change to:

`    private void runUpdateCheckerConsoleUpdateCheck() {
        new UpdateChecker(this, UpdateCheckSource.SPIGOT, "" + SPIGOT_RESOURCE_ID+ "")
                .setDownloadLink("https://www.spigotmc.org/resources/armorstandeditor-reborn.94503/")
                .setChangelogLink("https://www.spigotmc.org/resources/armorstandeditor-reborn.94503/history")
                .setColoredConsoleOutput(true)
                .setUserAgent(new UserAgentBuilder().addPluginNameAndVersion().addServerVersion())
                .checkEveryXHours(72) //Warn people every 72 hours
                .checkNow();
    }`
    
There would also be a second method that does the distinct OP Notify as well and we check in commandEx for the config option and the update permission as we assume if User has asedit.update they want the notifications for updates ;)

**Comment by mibby** [comment]
Looks good to me. Personally would prefer avoiding update checks entirely to reduce http calls, but console only is fine when opUpdateNotification is false.

**Comment by mibby** [comment]
Seems to be functional, thanks. No longer getting the notification when logging in.

Would it be possible to add a sanity check for versions greater than Spigot release to not output a new version message in console though?

```
[05:19:05] [Server thread/WARN]: [ArmorStandEditor] ***********************************************************************
[05:19:05] [Server thread/WARN]: [ArmorStandEditor] * There is a new version of ArmorStandEditor available!
[05:19:05] [Server thread/WARN]: [ArmorStandEditor] *  
[05:19:05] [Server thread/WARN]: [ArmorStandEditor] * Your version:   1.19.x-36
[05:19:05] [Server thread/WARN]: [ArmorStandEditor] * Latest version: 1.19-35
[05:19:05] [Server thread/WARN]: [ArmorStandEditor] *  
[05:19:05] [Server thread/WARN]: [ArmorStandEditor] * Please update to the newest version.
[05:19:05] [Server thread/WARN]: [ArmorStandEditor] *  
[05:19:05] [Server thread/WARN]: [ArmorStandEditor] * Download:
[05:19:05] [Server thread/WARN]: [ArmorStandEditor] *   https://www.spigotmc.org/resources/armorstandeditor-reborn.94503/
[05:19:05] [Server thread/WARN]: [ArmorStandEditor] ***********************************************************************
```

**Comment by Wolfieheart** [comment]
Yeah that should be easily implemented. Lemme check the UpdateChecker API for that.

**Comment by Wolfieheart** [comment]
Added. Have it hardchecking the Version in the Config.yml and if it is .x then it just returns, otherwise it does the check :)
