### ISSUE TITLE
[Bug]: Debug info writing to log file despite debug: false

### ISSUE THREAD

**Issue by mibby** [Wolfieheart/ArmorStandEditor#87]
### Expected behavior

No DEBUG-year-month-day.log files to be created.

### Observed/Actual behavior

DEBUG log files are being created in /ArmorStandEditor/ plugin folder.

### Steps/models to reproduce

* Type an ASE command such as /ase.
* See new log

DEBUG-2022-06-24.log
```
24/06/2022, 02:17: Sending List of Commands to: §4mibby§r
24/06/2022, 02:17: Sending List of Commands to: §mibby§r
```

### Plugin list

ArmorStandEditor
ProtocolLib

### Plugin Version

https://github.com/Wolfieheart/ArmorStandEditor/actions/runs/2544848407

### Server Version

Paper dev 36 (Spigot 1.19)

### Other

config.yml
```
#DO NOT ENABLE - For Testing Purposes. Can lead to unwanted side effects
#Enable if you are submitting a bug report PLEASE!
debug: false
```

**Comment by Wolfieheart** [comment]
This one I keep having mixed results, might have remove debug output entirely which is fine as well for me since I really shouldnt have it in a production build, at least for now til I can work out why this doesnt happen on Test ENV

**Comment by Wolfieheart** [comment]
It makes sense to remove it til I have a better fix for it. So Imma do that and if needs be and someone wants to implement debug ffeatures, by all means do so but create a PR for it from Dev :)

**Comment by Sikatsu** [comment]
No update on this yet? I am running the one from spigot but it still happens.

**Comment by Wolfieheart** [comment]
Already fixed (and removed) in Dev on https://github.com/Wolfieheart/ArmorStandEditor/pull/84/commits/d383751cb4c3cf8276241b4555109a2dd1dcb629
